## Algo Trading Notebook

In [ ]:
#This notebook has issues

In [10]:
%matplotlib inline
import os
import requests
import pandas as pd
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
import matplotlib.pyplot as plt
import hvplot.pandas
import numpy as np
import seaborn as sns
from pathlib import Path

In [ ]:
# Define function to create Pickle File
def get_api_dataframe():
    # Set Alpaca API key and secret

    load_dotenv()
    api_key= os.getenv("ALPACA_API_KEY")
    sec_key= os.getenv("ALPACA_SECRET_KEY")

# Create the Alpaca API object

    alpaca = tradeapi.REST(
        api_key,
        sec_key,
        api_version="v2"
    )
# Get 3 years worth of historical data for Alcohol stocks, Cannabis Stocks, and S&P 500

    start_date = pd.Timestamp('2019-04-20', tz='America/New_York').isoformat()
    end_date = pd.Timestamp('2022-04-20', tz='America/New_York').isoformat()

    tickers = ["BUD", "DEO", "SAM", "TAP", "STZ","VFF","JAZZ","CRON", "TLRY","CGC", "SPY"]

# Set timeframe to "1Day" for Alpaca API
    timeframe = "1Day"

# Get current closing prices for All Stocks

    df_stock_data = alpaca.get_bars(
        tickers,
        timeframe,
        start = start_date,
        end = end_date
    ).df

#Set index to date
    df_stock_data.index = df_stock_data.index.date
    return df_stock_data

In [ ]:
# Check if file exists
# If file does not exist then load api and save file
# else read data from pikl

api_data_file = Path("api_data.pkl")
if api_data_file.is_file():
    print ("API data file exists")
    df_stock_data = pd.read_pickle(api_data_file)
else:
    print ("API file does not exist") 
    df_stock_data = get_api_dataframe()
    df_stock_data.to_pickle(api_data_file)

#View dataframe
df_stock_data.head(-5)

In [ ]:
#df_stock_data.rename(index={0:'date'}, inplace=True)

In [ ]:
df_stock_data.head()

In [ ]:
#df_stock_data.to_csv('api_call.csv')

In [11]:

df_stock_data = pd.read_csv(
    Path("api_data.csv"), 
    index_col="date", 
    infer_datetime_format=True, 
    parse_dates=True
)
df_stock_data.head()

,open,high,low,close,volume,trade_count,vwap,symbol
date,,,,,,,,
2019-04-22,89.69,90.470,89.58,89.60,970834,9479,90.000447,BUD
2019-04-23,88.56,89.790,88.50,89.25,755451,7907,89.242818,BUD
2019-04-24,89.02,89.130,87.82,88.21,1038366,11509,88.324096,BUD
2019-04-25,86.89,87.020,86.00,86.64,1341678,13124,86.467163,BUD
2019-04-26,87.38,87.625,86.83,87.58,920430,9005,87.292918,BUD

In [ ]:
#df_stock_data.columns = ['Date', 'open', 'high', 'low', 'close', 'volume', 'trade_count', 'vwap', 'symbol']

In [ ]:
#df_stock_data['Date'] = pd.to_datetime(df_stock_data['Date'])

In [12]:
# Calculate the daily returns using the closing prices and the pct_change function
df_stock_data["actual_returns"] = df_stock_data["close"].pct_change()

# Display sample data
df_stock_data.head()

,open,high,low,close,volume,trade_count,vwap,symbol,actual_returns
date,,,,,,,,,
2019-04-22,89.69,90.470,89.58,89.60,970834,9479,90.000447,BUD,NaN
2019-04-23,88.56,89.790,88.50,89.25,755451,7907,89.242818,BUD,-0.003906
2019-04-24,89.02,89.130,87.82,88.21,1038366,11509,88.324096,BUD,-0.011653
2019-04-25,86.89,87.020,86.00,86.64,1341678,13124,86.467163,BUD,-0.017798
2019-04-26,87.38,87.625,86.83,87.58,920430,9005,87.292918,BUD,0.010849

In [13]:
# Drop all NaN values from the DataFrame
df_stock_data = df_stock_data.dropna()

# Review the DataFrame
display(df_stock_data.head())
display(df_stock_data.tail())

,open,high,low,close,volume,trade_count,vwap,symbol,actual_returns
date,,,,,,,,,
2019-04-23,88.56,89.790,88.50,89.25,755451,7907,89.242818,BUD,-0.003906
2019-04-24,89.02,89.130,87.82,88.21,1038366,11509,88.324096,BUD,-0.011653
2019-04-25,86.89,87.020,86.00,86.64,1341678,13124,86.467163,BUD,-0.017798
2019-04-26,87.38,87.625,86.83,87.58,920430,9005,87.292918,BUD,0.010849
2019-04-29,87.35,88.370,87.27,88.01,840389,8728,87.936270,BUD,0.004910

,open,high,low,close,volume,trade_count,vwap,symbol,actual_returns
date,,,,,,,,,
2022-04-13,4.75,4.91,4.72,4.88,286697,3324,4.838941,VFF,0.027368
2022-04-14,4.89,4.92,4.69,4.69,385134,3018,4.797960,VFF,-0.038934
2022-04-18,4.70,4.70,4.40,4.47,588755,6521,4.504151,VFF,-0.046908
2022-04-19,4.45,4.60,4.34,4.52,533863,4550,4.478629,VFF,0.011186
2022-04-20,4.57,4.62,4.39,4.45,326564,3916,4.478399,VFF,-0.015487

In [14]:
#Create Feature Set and Window Sizes
# Define a window size of 4
short_window = 4

# Create an SMA that uses short_window, and assign it to a new column named “sma_fast”
df_stock_data["sma_fast"] = df_stock_data["close"].rolling(window=short_window).mean()


# Define a window size of 20
long_window = 20

# Create an SMA that uses long_window, and assign it to a new columns named “sma_slow”
df_stock_data["sma_slow"] = df_stock_data["close"].rolling(window=long_window).mean()

In [15]:
# Drop the NaNs using dropna()
df_stock_data = df_stock_data.dropna()

In [16]:
# Assign a copy of the `sma_fast` and `sma_slow` columns to a new DataFrame called `X`
X = df_stock_data[["sma_fast", "sma_slow"]].shift().dropna().copy()

# Display sample data
display(X.head())
display(X.tail())

            sma_fast  sma_slow
date
2019-05-21   82.8400   85.7115
2019-05-22   82.1325   85.2990
2019-05-23   81.8175   85.0195
2019-05-24   81.7325   84.8025
2019-05-28   82.1700   84.5615

            sma_fast  sma_slow
date
2022-04-13    4.8575    5.3140
2022-04-14    4.8175    5.3180
2022-04-18    4.7825    5.3025
2022-04-19    4.6975    5.2610
2022-04-20    4.6400    5.2225

In [17]:
#Create Target Set
# Create a new column in the `df_stock_data` called "signal" setting its value to zero.
df_stock_data["signal"] = 0.0

# Create the signal to buy
df_stock_data.loc[(df_stock_data["actual_returns"] >= 0), "signal"] = 1

# Create the signal to sell
df_stock_data.loc[(df_stock_data["actual_returns"] < 0), "signal"] = -1

In [18]:
# Copy the new "signal" column to a new Series called `y`.
y = df_stock_data["signal"].copy()

In [34]:
len(y)

8307

In [28]:
#Split the Data in Training and Test Sets
# Import required libraries
from pandas.tseries.offsets import DateOffset

# Select the start of the training period
training_begin = X.index.min() + DateOffset(months=1)

# Display the training begin date
print(training_begin)

2019-05-22 00:00:00

In [29]:
# Select the ending period for the training data with an offset of 18 months
training_end = X.index.min() + DateOffset(months=4)

# Display the training end date
print(training_end)

2019-08-22 00:00:00

In [30]:
X.index.min()

Timestamp('2019-04-22 00:00:00')

In [31]:
X.index

DatetimeIndex(['2019-05-21', '2019-05-22', '2019-05-23', '2019-05-24',
               '2019-05-28', '2019-05-29', '2019-05-30', '2019-05-31',
               '2019-06-03', '2019-06-04',
               ...
               '2022-04-06', '2022-04-07', '2022-04-08', '2022-04-11',
               '2022-04-12', '2022-04-13', '2022-04-14', '2022-04-18',
               '2022-04-19', '2022-04-20'],
              dtype='datetime64[ns]', name='date', length=8306, freq=None)

In [32]:
# Generate the X_train and y_train DataFrames
X_train = X.loc[training_begin:training_end]
y_train = y.loc[training_begin:training_end]

KeyError: "Cannot get left slice bound for non-unique label: Timestamp('2019-05-22 00:00:00')"

In [22]:
# Generate the X_test and y_test DataFrames
X_test = X.loc[training_end:]
y_test = y.loc[training_end:]

KeyError: "Cannot get left slice bound for non-unique label: Timestamp('2019-08-22 00:00:00')"

In [ ]:
#Standardize the Data
# Import required libraries
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler instance
scaler = StandardScaler()
 
# Apply the scaler model to fit the X-train data
X_scaler = scaler.fit(X_train)
 
# Transform the X_train and X_test DataFrames using the X_scaler
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
#df_stock_data.loc[:["close"]]

In [ ]:
all_close_prices = df_stock_data.pivot(values=["close","volume"], columns= "symbol")
all_close_prices